### 1.Create a null vector of size 10 but the fifth value which is 

In [1]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2.Create a vector with values ranging from 10 to 49

In [2]:
import numpy as np
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 3.Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


### 5.Create a 10x10 array with random values and find the minimum and maximum values

In [5]:
import numpy as np
random_array = np.random.rand(10, 10)
minimum_value = random_array.min()
maximum_value = random_array.max()
print(random_array)
print(f"Minimum Value: {minimum_value}")
print(f"Maximum Value: {maximum_value}")

[[0.65353604 0.06588043 0.09967505 0.85600518 0.7866889  0.25806496
  0.23613454 0.27020636 0.59471876 0.99006454]
 [0.87862176 0.24750671 0.18460872 0.62794627 0.54514471 0.75320951
  0.5106932  0.95384928 0.69165977 0.20343383]
 [0.6484329  0.12581185 0.26541648 0.11710754 0.42506449 0.68850228
  0.73204601 0.2790406  0.42161189 0.08291205]
 [0.01419602 0.23428395 0.56954121 0.59353833 0.59001108 0.46759229
  0.45030057 0.40942675 0.09521343 0.85243816]
 [0.61870122 0.65892176 0.9457677  0.36585093 0.95728788 0.11154091
  0.37795397 0.89521273 0.40647364 0.34294088]
 [0.80924396 0.43652873 0.67664944 0.75943183 0.02355294 0.77380437
  0.32038522 0.5745666  0.37607327 0.73102561]
 [0.44022849 0.60678328 0.900375   0.31631328 0.23710366 0.96551703
  0.34887301 0.97982474 0.975187   0.22987942]
 [0.06887049 0.57414258 0.66763388 0.38043652 0.43918863 0.6857761
  0.05227122 0.89029209 0.56382861 0.03158721]
 [0.60666764 0.58963785 0.34023972 0.12489812 0.97884254 0.79469652
  0.27408947 

### 6.Create a random vector of size 30 and find the mean value.

In [6]:
import numpy as np
random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print(random_vector)
print(f"Mean Value: {mean_value}")

[0.0341132  0.50523274 0.37928977 0.78481797 0.50931469 0.40295405
 0.2010417  0.76676106 0.54818195 0.05573543 0.45443241 0.98209034
 0.06779783 0.41563967 0.94403993 0.58573963 0.28435263 0.00903895
 0.17520877 0.16531526 0.76118624 0.18718329 0.97151188 0.64241854
 0.13569089 0.65523329 0.08080307 0.89105314 0.87617683 0.93802502]
Mean Value: 0.4803460067880673
